version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://mernecommerce-frontend --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist
