version: 0.2

phases:
  install:
    commands: []
  build:
    commands: []
  post_build:
    commands:
      - echo Deploying dist folder to S3...
      - aws s3 sync dist/ s3://mernecommerce-frontend --delete
