version: 0.2

phases:
  install:
    commands: []
  build:
    commands: []
  post_build:
    commands:
      - echo Deploying files to S3...
      - aws s3 sync . s3://mernecommerce-frontend --delete
