version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install."
  build:
    commands:
      - echo "No build step needed."
  post_build:
    commands:
      - echo "Deploying dist/ to S3..."
      - aws s3 sync dist/ s3://mernecommerce-frontend --delete

artifacts:
  files:
    - '**/*'
  base-directory: dist
